-- ================================================================
-- OurT 프로젝트: 기능 테이블 생성 (Supabase SQL Editor에서 실행)
-- ================================================================

-- ── 커뮤니티 게시글 ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS community_posts (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    content      TEXT NOT NULL,
    flower_species VARCHAR(100),
    image_url    VARCHAR(1024),
    latitude     DOUBLE PRECISION,
    longitude    DOUBLE PRECISION,
    address      VARCHAR(255),
    like_count   INT NOT NULL DEFAULT 0,
    created_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_community_posts_user    ON community_posts(user_id);
CREATE INDEX IF NOT EXISTS idx_community_posts_created ON community_posts(created_at DESC);

-- ── 게시글 좋아요 ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS post_likes (
    user_id  BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    post_id  BIGINT NOT NULL REFERENCES community_posts(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    PRIMARY KEY (user_id, post_id)
);

-- ── 게시글 저장 ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS saved_posts (
    user_id  BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    post_id  BIGINT NOT NULL REFERENCES community_posts(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    PRIMARY KEY (user_id, post_id)
);

-- ── 꽃 스팟 저장 ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS saved_spots (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name           VARCHAR(100) NOT NULL,
    flower_species VARCHAR(100),
    address        VARCHAR(255),
    latitude       DOUBLE PRECISION,
    longitude      DOUBLE PRECISION,
    bloom_period   VARCHAR(100),
    created_at     TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_saved_spots_user ON saved_spots(user_id);

-- ── 걷기 기록 (일별) ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS walk_records (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    record_date   DATE NOT NULL,
    step_count    INT NOT NULL DEFAULT 0,
    points_earned INT NOT NULL DEFAULT 0,
    created_at    TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE (user_id, record_date)
);

CREATE INDEX IF NOT EXISTS idx_walk_records_user_date ON walk_records(user_id, record_date DESC);

-- ── users 테이블에 포인트 잔액 컬럼 추가 ─────────────────────
ALTER TABLE users ADD COLUMN IF NOT EXISTS point_balance INT NOT NULL DEFAULT 0;
