-- ================================================================
-- OurT 꽃 도감 테이블 (Supabase SQL Editor에서 실행)
-- 초기화 후 재실행 시: DROP 먼저 실행 후 나머지 실행
-- ================================================================

-- ── 초기화 (순서 중요 — 참조 테이블부터) ────────────────────────
DROP TABLE IF EXISTS flower_species_mapping;
DROP TABLE IF EXISTS flower_book;
DROP TABLE IF EXISTS flowers;
DROP TABLE IF EXISTS flower_categories;

-- ── 포괄 카테고리 (속/종 기준으로 묶음) ──────────────────────
CREATE TABLE IF NOT EXISTS flower_categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50) NOT NULL UNIQUE,
    emoji       VARCHAR(10),
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

INSERT INTO flower_categories (name, emoji) VALUES
    -- 봄꽃
    ('벚꽃',     '🌸'),  -- Prunus (벚나무속 전체)
    ('매화',     '🤍'),  -- Prunus mume
    ('목련',     '🪷'),  -- Magnolia
    ('개나리',   '💛'),  -- Forsythia
    ('진달래',   '🌺'),  -- Rhododendron (진달래, 철쭉, 영산홍)
    ('수선화',   '🌼'),  -- Narcissus
    ('튤립',     '🌷'),  -- Tulipa
    ('히아신스', '💙'),  -- Hyacinthus
    ('프리지아', '🌻'),  -- Freesia
    ('라일락',   '💜'),  -- Syringa
    -- 여름꽃
    ('장미',     '🌹'),  -- Rosa
    ('수국',     '💠'),  -- Hydrangea
    ('백합',     '🤍'),  -- Lilium
    ('연꽃',     '🪷'),  -- Nelumbo / Nymphaea (수련 포함)
    ('해바라기', '🌻'),  -- Helianthus
    ('능소화',   '🧡'),  -- Campsis
    ('나팔꽃',   '💜'),  -- Ipomoea
    ('무궁화',   '🌸'),  -- Hibiscus (국화)
    ('봉선화',   '🌺'),  -- Impatiens
    ('채송화',   '🌸'),  -- Portulaca
    -- 가을꽃
    ('국화',     '🌼'),  -- Chrysanthemum / Dendranthema
    ('코스모스', '🩷'),  -- Cosmos
    ('루드베키아','🌻'), -- Rudbeckia (원추천인국)
    ('달리아',   '🌸'),  -- Dahlia
    ('맨드라미', '🔴'),  -- Celosia
    -- 겨울/사계절
    ('동백',     '🔴'),  -- Camellia
    ('라벤더',   '💜'),  -- Lavandula
    -- 주요 초화류
    ('작약',     '🌸'),  -- Paeonia (모란 포함)
    ('도라지',   '💜'),  -- Platycodon
    ('민들레',   '💛'),  -- Taraxacum
    ('제비꽃',   '💜'),  -- Viola (팬지 포함)
    ('금잔화',   '🟠'),  -- Calendula
    ('과꽃',     '💜'),  -- Callistephus
    ('살비아',   '🔵'),  -- Salvia
    ('베고니아', '🌸'),  -- Begonia
    ('페튜니아', '💜'),  -- Petunia
    ('글라디올러스','🌺'),-- Gladiolus
    ('칸나',     '🔴'),  -- Canna
    ('기타',     '🌿')   -- 미분류
ON CONFLICT (name) DO NOTHING;

-- ── 꽃 도감 (농사로 API 데이터) ──────────────────────────────
CREATE TABLE IF NOT EXISTS flower_book (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_no          VARCHAR(20) UNIQUE,
    name             VARCHAR(100) NOT NULL,
    scientific_name  VARCHAR(200),
    bloom_month      INT,
    bloom_day        INT,
    flower_language  TEXT,
    description      TEXT,
    grow_tips        TEXT,
    image_url        VARCHAR(1024),
    category_id      BIGINT REFERENCES flower_categories(id),
    source           VARCHAR(20) NOT NULL DEFAULT 'NONGSARO', -- NONGSARO | WIKIPEDIA | MANUAL
    status           VARCHAR(20) NOT NULL DEFAULT 'COMPLETE', -- COMPLETE | AUTO | PENDING
    created_at       TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_flower_book_name       ON flower_book(name);
CREATE INDEX IF NOT EXISTS idx_flower_book_scientific ON flower_book(scientific_name);
CREATE INDEX IF NOT EXISTS idx_flower_book_category   ON flower_book(category_id);
CREATE INDEX IF NOT EXISTS idx_flower_book_month      ON flower_book(bloom_month);

-- ── 꽃 명소 (GPS 기반 게시글, 챗봇 FlowerTools 사용) ─────────
CREATE TABLE IF NOT EXISTS flowers (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(100) NOT NULL,
    species           VARCHAR(200) NOT NULL,
    address           VARCHAR(255) NOT NULL,
    lat               DOUBLE PRECISION NOT NULL,
    lng               DOUBLE PRECISION NOT NULL,
    bloom_start       VARCHAR(50),
    bloom_end         VARCHAR(50),
    description       VARCHAR(1000),
    thumbnail_url     VARCHAR(1024),
    status            VARCHAR(20) NOT NULL DEFAULT 'BLOOMING',
    approval_status   VARCHAR(20) NOT NULL DEFAULT 'APPROVED',
    verification_count INT NOT NULL DEFAULT 0,
    created_at        TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_flowers_approval ON flowers(approval_status);
CREATE INDEX IF NOT EXISTS idx_flowers_species  ON flowers(species);

-- ── AI 학명 → 카테고리 매핑 ──────────────────────────────────
CREATE TABLE IF NOT EXISTS flower_species_mapping (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ai_name      VARCHAR(200) NOT NULL UNIQUE,
    category_id  BIGINT REFERENCES flower_categories(id),
    created_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_species_mapping_name ON flower_species_mapping(ai_name);

-- 속명(genus) 매핑 — Plant.id가 반환하는 학명의 첫 단어 기준
INSERT INTO flower_species_mapping (ai_name, category_id) VALUES
    -- 벚꽃류
    ('Prunus',            (SELECT id FROM flower_categories WHERE name = '벚꽃')),
    ('Prunus serrulata',  (SELECT id FROM flower_categories WHERE name = '벚꽃')),
    ('Prunus yedoensis',  (SELECT id FROM flower_categories WHERE name = '벚꽃')),
    ('Prunus × yedoensis',(SELECT id FROM flower_categories WHERE name = '벚꽃')),
    ('Cerasus',           (SELECT id FROM flower_categories WHERE name = '벚꽃')),
    -- 매화
    ('Prunus mume',       (SELECT id FROM flower_categories WHERE name = '매화')),
    -- 목련류
    ('Magnolia',          (SELECT id FROM flower_categories WHERE name = '목련')),
    ('Liriodendron',      (SELECT id FROM flower_categories WHERE name = '목련')),
    ('Michelia',          (SELECT id FROM flower_categories WHERE name = '목련')),
    -- 개나리류
    ('Forsythia',         (SELECT id FROM flower_categories WHERE name = '개나리')),
    -- 진달래류
    ('Rhododendron',      (SELECT id FROM flower_categories WHERE name = '진달래')),
    ('Azalea',            (SELECT id FROM flower_categories WHERE name = '진달래')),
    -- 수선화류
    ('Narcissus',         (SELECT id FROM flower_categories WHERE name = '수선화')),
    -- 튤립류
    ('Tulipa',            (SELECT id FROM flower_categories WHERE name = '튤립')),
    -- 히아신스류
    ('Hyacinthus',        (SELECT id FROM flower_categories WHERE name = '히아신스')),
    ('Muscari',           (SELECT id FROM flower_categories WHERE name = '히아신스')),
    -- 프리지아
    ('Freesia',           (SELECT id FROM flower_categories WHERE name = '프리지아')),
    -- 라일락
    ('Syringa',           (SELECT id FROM flower_categories WHERE name = '라일락')),
    -- 장미류
    ('Rosa',              (SELECT id FROM flower_categories WHERE name = '장미')),
    -- 수국류
    ('Hydrangea',         (SELECT id FROM flower_categories WHERE name = '수국')),
    -- 백합류
    ('Lilium',            (SELECT id FROM flower_categories WHERE name = '백합')),
    ('Hemerocallis',      (SELECT id FROM flower_categories WHERE name = '백합')),
    -- 연꽃/수련류
    ('Nelumbo',           (SELECT id FROM flower_categories WHERE name = '연꽃')),
    ('Nymphaea',          (SELECT id FROM flower_categories WHERE name = '연꽃')),
    -- 해바라기류
    ('Helianthus',        (SELECT id FROM flower_categories WHERE name = '해바라기')),
    -- 능소화류
    ('Campsis',           (SELECT id FROM flower_categories WHERE name = '능소화')),
    -- 나팔꽃류
    ('Ipomoea',           (SELECT id FROM flower_categories WHERE name = '나팔꽃')),
    -- 무궁화
    ('Hibiscus',          (SELECT id FROM flower_categories WHERE name = '무궁화')),
    -- 봉선화
    ('Impatiens',         (SELECT id FROM flower_categories WHERE name = '봉선화')),
    -- 채송화
    ('Portulaca',         (SELECT id FROM flower_categories WHERE name = '채송화')),
    -- 국화류
    ('Chrysanthemum',     (SELECT id FROM flower_categories WHERE name = '국화')),
    ('Dendranthema',      (SELECT id FROM flower_categories WHERE name = '국화')),
    ('Leucanthemum',      (SELECT id FROM flower_categories WHERE name = '국화')),
    -- 코스모스
    ('Cosmos',            (SELECT id FROM flower_categories WHERE name = '코스모스')),
    -- 루드베키아
    ('Rudbeckia',         (SELECT id FROM flower_categories WHERE name = '루드베키아')),
    ('Echinacea',         (SELECT id FROM flower_categories WHERE name = '루드베키아')),
    -- 달리아
    ('Dahlia',            (SELECT id FROM flower_categories WHERE name = '달리아')),
    -- 맨드라미
    ('Celosia',           (SELECT id FROM flower_categories WHERE name = '맨드라미')),
    -- 동백
    ('Camellia',          (SELECT id FROM flower_categories WHERE name = '동백')),
    -- 라벤더
    ('Lavandula',         (SELECT id FROM flower_categories WHERE name = '라벤더')),
    -- 작약/모란
    ('Paeonia',           (SELECT id FROM flower_categories WHERE name = '작약')),
    -- 도라지
    ('Platycodon',        (SELECT id FROM flower_categories WHERE name = '도라지')),
    -- 민들레
    ('Taraxacum',         (SELECT id FROM flower_categories WHERE name = '민들레')),
    -- 제비꽃/팬지
    ('Viola',             (SELECT id FROM flower_categories WHERE name = '제비꽃')),
    -- 금잔화
    ('Calendula',         (SELECT id FROM flower_categories WHERE name = '금잔화')),
    -- 과꽃
    ('Callistephus',      (SELECT id FROM flower_categories WHERE name = '과꽃')),
    -- 살비아
    ('Salvia',            (SELECT id FROM flower_categories WHERE name = '살비아')),
    -- 베고니아
    ('Begonia',           (SELECT id FROM flower_categories WHERE name = '베고니아')),
    -- 페튜니아
    ('Petunia',           (SELECT id FROM flower_categories WHERE name = '페튜니아')),
    -- 글라디올러스
    ('Gladiolus',         (SELECT id FROM flower_categories WHERE name = '글라디올러스')),
    -- 칸나
    ('Canna',             (SELECT id FROM flower_categories WHERE name = '칸나'))
ON CONFLICT (ai_name) DO NOTHING;
