-- ================================================================
-- OurT 꽃 도감 테이블 (Supabase SQL Editor에서 실행)
-- ================================================================

-- ── 포괄 카테고리 ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS flower_categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50) NOT NULL UNIQUE,   -- 벚꽃, 장미, 진달래 등
    emoji       VARCHAR(10),
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 기본 카테고리 삽입
INSERT INTO flower_categories (name, emoji) VALUES
    ('벚꽃',   '🌸'),
    ('장미',   '🌹'),
    ('진달래', '🌺'),
    ('국화',   '🌼'),
    ('튤립',   '🌷'),
    ('개나리', '💛'),
    ('수국',   '💜'),
    ('해바라기','🌻'),
    ('코스모스','🩷'),
    ('매화',   '🤍'),
    ('목련',   '🪷'),
    ('라벤더', '💜'),
    ('기타',   '🌿')
ON CONFLICT (name) DO NOTHING;

-- ── 꽃 도감 ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS flowers (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_no          VARCHAR(20) UNIQUE,          -- 농사로 고유번호
    name             VARCHAR(100) NOT NULL,        -- 꽃 이름
    scientific_name  VARCHAR(200),                 -- 학명 (Plant.id 매핑 핵심)
    bloom_month      INT,                          -- 개화월
    bloom_day        INT,                          -- 개화일
    flower_language  TEXT,                         -- 꽃말
    description      TEXT,                         -- 꽃 설명
    grow_tips        TEXT,                         -- 키우는 법
    image_url        VARCHAR(1024),                -- 이미지 URL
    category_id      BIGINT REFERENCES flower_categories(id),
    created_at       TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_flowers_name          ON flowers(name);
CREATE INDEX IF NOT EXISTS idx_flowers_scientific    ON flowers(scientific_name);
CREATE INDEX IF NOT EXISTS idx_flowers_category      ON flowers(category_id);
CREATE INDEX IF NOT EXISTS idx_flowers_bloom_month   ON flowers(bloom_month);

-- ── AI 학명 → 카테고리 매핑 ──────────────────────────────────
-- Plant.id가 반환한 학명을 카테고리로 연결하는 테이블
-- 3단계 매칭: 완전일치 → 속명(genus) → 여기서 수동 매핑
CREATE TABLE IF NOT EXISTS flower_species_mapping (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ai_name      VARCHAR(200) NOT NULL UNIQUE,  -- Plant.id 반환 학명 or 일반명
    category_id  BIGINT REFERENCES flower_categories(id),
    created_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_species_mapping_name ON flower_species_mapping(ai_name);

-- 주요 속명(genus) 매핑 사전 등록
INSERT INTO flower_species_mapping (ai_name, category_id) VALUES
    ('Prunus',       (SELECT id FROM flower_categories WHERE name = '벚꽃')),
    ('Rosa',         (SELECT id FROM flower_categories WHERE name = '장미')),
    ('Rhododendron', (SELECT id FROM flower_categories WHERE name = '진달래')),
    ('Chrysanthemum',(SELECT id FROM flower_categories WHERE name = '국화')),
    ('Tulipa',       (SELECT id FROM flower_categories WHERE name = '튤립')),
    ('Forsythia',    (SELECT id FROM flower_categories WHERE name = '개나리')),
    ('Hydrangea',    (SELECT id FROM flower_categories WHERE name = '수국')),
    ('Helianthus',   (SELECT id FROM flower_categories WHERE name = '해바라기')),
    ('Cosmos',       (SELECT id FROM flower_categories WHERE name = '코스모스')),
    ('Prunus mume',  (SELECT id FROM flower_categories WHERE name = '매화')),
    ('Magnolia',     (SELECT id FROM flower_categories WHERE name = '목련')),
    ('Lavandula',    (SELECT id FROM flower_categories WHERE name = '라벤더'))
ON CONFLICT (ai_name) DO NOTHING;
