spring:
  application:
    name: flower-backend
  profiles:
    include: auth  # application-auth.yml 자동으로 읽어옴
  datasource:
    url: jdbc:postgresql://localhost:5432/flower_db
    username: flower
    password: flower_pwd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
    open-in-view: false
